# GitHub Actions Workflow for User Onboarding
# This workflow is triggered when a new user creation issue is opened
# It processes the form data and runs the onboarding script

name: User Onboarding Workflow

# Trigger: This workflow runs when issues are opened or labeled
on:
  issues:
    types: [opened, labeled]

# Define the jobs to run
jobs:
  # Job 1: Process user creation form
  process-user-creation:
    # Only run if the issue has the "user" label (from our form)
    if: contains(github.event.issue.labels.*.name, 'user')

    # Run on Ubuntu (we'll change this to Windows later for PowerShell)
    runs-on: ubuntu-latest

    # Define the steps in this job
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Extract form data from the issue body
      - name: Extract User Data
        id: extract-data
        run: |
          echo "This is where we'll extract form data"
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"

      # Step 3: Create CSV file (placeholder for now)
      - name: Create CSV File
        run: |
          echo "This is where we'll create the CSV file"

      # Step 4: Run PowerShell script (placeholder for now)
      - name: Run Onboarding Script
        run: |
          echo "This is where we'll run the PowerShell script"

      # Step 5: Comment back on the issue with results
      - name: Comment on Issue
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 User onboarding process started! This is a test comment.'
            })
